"""agregar_poligono_a_proyecto

Revision ID: 0020939e1424
Revises: b3f496d19242
Create Date: 2026-07-25 16:06:05.578196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '0020939e1424'
down_revision: Union[str, Sequence[str], None] = 'b3f496d19242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyecto', sa.Column('poligono', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    # Crear índice GiST solo si no existe
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_proyecto_poligono 
        ON proyecto USING gist (poligono)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_proyecto_poligono', table_name='proyecto', postgresql_using='gist')
    op.drop_column('proyecto', 'poligono')
    # ### end Alembic commands ###
