"""restructurar_tabla_medidas

Revision ID: 8efd55459ad0
Revises: 1072dba99881
Create Date: 2026-07-25 15:46:53.532838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8efd55459ad0'
down_revision: Union[str, Sequence[str], None] = '1072dba99881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medida', sa.Column('numero_medicion', sa.Float(), nullable=False))
    op.add_column('medida', sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('medida', sa.Column('fecha_hora', sa.DateTime(), nullable=False))
    op.add_column('medida', sa.Column('x', sa.Float(), nullable=False))
    op.add_column('medida', sa.Column('y', sa.Float(), nullable=False))
    op.add_column('medida', sa.Column('elevacion', sa.Float(), nullable=True))
    op.add_column('medida', sa.Column('altura_ortometrica', sa.Float(), nullable=True))
    op.add_column('medida', sa.Column('altura_instrumento', sa.Float(), nullable=True))
    op.add_column('medida', sa.Column('fix_id', sa.Float(), nullable=True))
    op.add_column('medida', sa.Column('velocidad', sa.Float(), nullable=True))
    op.add_column('medida', sa.Column('rumbo', sa.Float(), nullable=True))
    op.add_column('medida', sa.Column('precision_horizontal', sa.Float(), nullable=True))
    op.add_column('medida', sa.Column('precision_vertical', sa.Float(), nullable=True))
    op.add_column('medida', sa.Column('pdop', sa.Float(), nullable=True))
    op.add_column('medida', sa.Column('hdop', sa.Float(), nullable=True))
    op.add_column('medida', sa.Column('vdop', sa.Float(), nullable=True))
    op.add_column('medida', sa.Column('datos_adicionales', sa.JSON(), nullable=True))
    op.drop_column('medida', 'numero')
    op.drop_column('medida', 'fecha_modificacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medida', sa.Column('fecha_modificacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('medida', sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('medida', 'datos_adicionales')
    op.drop_column('medida', 'vdop')
    op.drop_column('medida', 'hdop')
    op.drop_column('medida', 'pdop')
    op.drop_column('medida', 'precision_vertical')
    op.drop_column('medida', 'precision_horizontal')
    op.drop_column('medida', 'rumbo')
    op.drop_column('medida', 'velocidad')
    op.drop_column('medida', 'fix_id')
    op.drop_column('medida', 'altura_instrumento')
    op.drop_column('medida', 'altura_ortometrica')
    op.drop_column('medida', 'elevacion')
    op.drop_column('medida', 'y')
    op.drop_column('medida', 'x')
    op.drop_column('medida', 'fecha_hora')
    op.drop_column('medida', 'observaciones')
    op.drop_column('medida', 'numero_medicion')
    # ### end Alembic commands ###
