"""agregar_foreign_key_proyecto

Revision ID: b3f496d19242
Revises: 8efd55459ad0
Create Date: 2026-07-25 16:04:33.143302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b3f496d19242'
down_revision: Union[str, Sequence[str], None] = '8efd55459ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'medida', 'proyecto', ['id_proyecto'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medida', type_='foreignkey')
    # ### end Alembic commands ###
